name: ripplearc_linter_example
description: Example usage of custom_lint_library
version: 1.0.0

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  mockito: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.25.0
  custom_lint: ^0.8.1
  flutter_lints: ^3.0.1
  ripplearc_linter:
    path: ../