name: ripplearc_flutter_lint
description: A custom lint library providing rules like prefer_fake_over_mock for better testing practices
version: 0.1.0
repository: https://github.com/ripplearc/ripplearc-flutter-lint

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  custom_lint_builder: 0.7.5
  analyzer: 7.3.0
  analyzer_plugin: 0.13.0
  source_span: 1.10.1

dev_dependencies:
  test: 1.26.2 