#!/bin/bash
#
# create_linter_rule_from_spec.sh
#
# Purpose:
#   Git/PR automation for new custom linter rules.
#   Called by the Cursor agent after it has generated all rule files.
#   See .cursor/rules/create-linter-rule.mdc for the full agent workflow.
#
# Usage:
#   ./scripts/create_linter_rule_from_spec.sh <rule_name> [base_branch]
#
# Arguments:
#   rule_name   (required) snake_case name of the rule, e.g. forbid_datetime_now
#   base_branch (optional) branch to open the PR against. Default: main
#
# Requirements:
#   - Git repository with only the new rule files changed.
#   - For PR creation: gh (GitHub CLI) installed and authenticated.
#     If gh is not available, the script prints a compare URL instead.
#

set -eo pipefail

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_open_compare_url() {
  local base="$1" head="$2" origin_url
  origin_url=$(git remote get-url origin 2>/dev/null | sed 's/\.git$//')
  [ -z "$origin_url" ] && return 1
  local url="${origin_url}/compare/${base}...${head}"
  echo "Open in browser to create the PR:"
  echo "  $url"
  command -v xdg-open >/dev/null 2>&1 && xdg-open "$url" 2>/dev/null && return 0
  command -v open      >/dev/null 2>&1 && open      "$url" 2>/dev/null && return 0
  return 0
}

_create_pr() {
  local base="$1" head="$2" rule="$3"
  if command -v gh >/dev/null 2>&1; then
    if gh pr view --head "$head" >/dev/null 2>&1; then
      echo "PR for branch $head already exists."
      gh pr view --web 2>/dev/null || true
    else
      gh pr create \
        --base "$base" --head "$head" \
        --title "Add ${rule} linter rule" \
        --body "Adds the \`${rule}\` custom linter rule.

- Analyzer: \`lib/core/analyzers/${rule}_analyzer.dart\`
- Rule:     \`lib/custom_lint_rules/${rule}.dart\`
- Registered in \`lib/ripplearc_linter.dart\`

Generated by the Cursor agent via \`.cursor/rules/create-linter-rule.mdc\`."
      echo "PR created."
    fi
  else
    echo "gh CLI not found."
    _open_compare_url "$base" "$head"
  fi
}

# ---------------------------------------------------------------------------
# Args
# ---------------------------------------------------------------------------

RULE_NAME="${1:-}"
BASE_BRANCH="${2:-main}"

if [ -z "$RULE_NAME" ]; then
  echo "Usage: $0 <rule_name> [base_branch]"
  echo "Example: $0 forbid_datetime_now"
  exit 1
fi

# Normalize: lowercase, spaces → underscore, hyphens → underscore
RULE_NAME=$(echo "$RULE_NAME" | tr '[:upper:]' '[:lower:]' | tr -s ' ' '_' | tr '-' '_')
BRANCH_NAME="rule/${RULE_NAME}"

# Always run from repo root
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$(cd "$SCRIPT_DIR/.." && pwd)"

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

if [ -z "$(git status --porcelain)" ]; then
  # Working tree is clean — if already on the rule branch, just (re-)push + create PR
  CURRENT=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || true)
  if [ "$CURRENT" = "$BRANCH_NAME" ]; then
    git push -u origin "$BRANCH_NAME" 2>/dev/null || true
    _create_pr "$BASE_BRANCH" "$BRANCH_NAME" "$RULE_NAME"
    exit 0
  fi
  echo "Error: no changes to commit."
  echo "Expected at least:"
  echo "  lib/core/analyzers/${RULE_NAME}_analyzer.dart"
  echo "  lib/custom_lint_rules/${RULE_NAME}.dart"
  echo "  lib/ripplearc_linter.dart (updated)"
  exit 1
fi

# Create or switch to rule branch (keeps working-tree changes)
if git rev-parse --verify "$BRANCH_NAME" >/dev/null 2>&1; then
  git checkout "$BRANCH_NAME"
else
  git checkout -b "$BRANCH_NAME"
fi

# Stage rule-related files
for f in \
  "lib/core/analyzers/${RULE_NAME}_analyzer.dart" \
  "lib/custom_lint_rules/${RULE_NAME}.dart" \
  "lib/ripplearc_linter.dart" \
  "test/custom_lint_rules/${RULE_NAME}_test.dart" \
  "example/example_${RULE_NAME}_rule.dart" \
  "docs/${RULE_NAME}.md"; do
  [ -f "$f" ] && git add "$f"
done

# Stage any other changes under standard rule directories
git add -A lib/ bin/ test/custom_lint_rules/ example/ docs/ rule_specs/ 2>/dev/null || true

git status
echo ""
git commit -m "Add ${RULE_NAME} linter rule"

echo "Pushing branch ${BRANCH_NAME}..."
git push -u origin "$BRANCH_NAME"

_create_pr "$BASE_BRANCH" "$BRANCH_NAME" "$RULE_NAME"

echo "Done."
