#!/bin/bash
#
# create_linter_rule_from_spec.sh
#
# Purpose:
#   Git/PR automation for a new linter rule. Creates the branch, stages
#   rule-related files, commits, pushes, and opens a PR.
#
#   Agent instructions live in .cursor/rules/create-linter-rule.mdc.
#   This script is meant to be run by the Cursor agent autonomously
#   after it has generated all rule files — not by the user manually.
#
# Usage:
#   ./scripts/create_linter_rule_from_spec.sh <rule_name> [base_branch]
#
# Arguments:
#   rule_name   (required) snake_case name of the rule, e.g. forbid_datetime_now
#   base_branch (optional) branch to open the PR against. Default: main
#
# Requirements:
#   - Run from any directory inside the repo.
#   - For PR creation: gh (GitHub CLI) installed and authenticated.
#     If gh is unavailable, the script prints the GitHub compare URL instead.
#

set -eo pipefail

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_open_pr_in_browser() {
  local base="$1" head="$2" origin_url pr_url
  origin_url=$(git remote get-url origin 2>/dev/null | sed 's/\.git$//')
  [ -z "$origin_url" ] && return 1
  pr_url="${origin_url}/compare/${base}...${head}"
  echo "Open in browser to create the PR: $pr_url"
  if   command -v xdg-open >/dev/null 2>&1; then xdg-open "$pr_url" 2>/dev/null && return 0
  elif command -v open     >/dev/null 2>&1; then open     "$pr_url" 2>/dev/null && return 0
  elif command -v start    >/dev/null 2>&1; then start    "$pr_url" 2>/dev/null && return 0
  fi
  return 1
}

_create_pr() {
  local base="$1" head="$2" rule="$3"
  if command -v gh >/dev/null 2>&1; then
    if gh pr view --head "$head" >/dev/null 2>&1; then
      echo "A PR for branch $head already exists."
      gh pr view --web 2>/dev/null || true
    else
      echo "Creating pull request..."
      gh pr create \
        --base "$base" --head "$head" \
        --title "Add ${rule} linter rule" \
        --body "Adds the \`${rule}\` custom linter rule.

- Analyzer: \`lib/core/analyzers/${rule}_analyzer.dart\`
- Rule:     \`lib/custom_lint_rules/${rule}.dart\`
- Registered in \`lib/ripplearc_linter.dart\`

Generated by the Cursor agent via \`.cursor/rules/create-linter-rule.mdc\`."
      echo "Done."
    fi
  else
    echo "gh not found — printing compare URL instead."
    _open_pr_in_browser "$base" "$head" || true
  fi
}

# ---------------------------------------------------------------------------
# Args
# ---------------------------------------------------------------------------

RULE_NAME="${1:-}"
BASE_BRANCH="${2:-main}"

if [ -z "$RULE_NAME" ]; then
  echo "Usage: $0 <rule_name> [base_branch]"
  echo "Example: $0 forbid_datetime_now"
  exit 1
fi

# Normalize: lowercase, spaces→underscores, hyphens→underscores
RULE_NAME=$(echo "$RULE_NAME" | tr '[:upper:]' '[:lower:]' | tr ' ' '_' | tr '-' '_')
BRANCH_NAME="rule/${RULE_NAME}"

# ---------------------------------------------------------------------------
# Repo root
# ---------------------------------------------------------------------------

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR/.."

# ---------------------------------------------------------------------------
# Already on branch with a clean tree → just push + open PR
# ---------------------------------------------------------------------------

if [ -z "$(git status --porcelain)" ]; then
  CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || true)
  if [ "$CURRENT_BRANCH" = "$BRANCH_NAME" ]; then
    git push -u origin "$BRANCH_NAME" 2>/dev/null || true
    _create_pr "$BASE_BRANCH" "$BRANCH_NAME" "$RULE_NAME"
    exit 0
  fi
  echo "Error: no changes to commit and not on branch $BRANCH_NAME."
  echo "Expected files:"
  echo "  lib/core/analyzers/${RULE_NAME}_analyzer.dart"
  echo "  lib/custom_lint_rules/${RULE_NAME}.dart"
  echo "  lib/ripplearc_linter.dart (updated)"
  exit 1
fi

# ---------------------------------------------------------------------------
# Create (or switch to) the rule branch, keeping working-tree changes
# ---------------------------------------------------------------------------

if git rev-parse --verify "$BRANCH_NAME" >/dev/null 2>&1; then
  git checkout "$BRANCH_NAME"
else
  git checkout -b "$BRANCH_NAME"
fi

# ---------------------------------------------------------------------------
# Stage rule-related files
# ---------------------------------------------------------------------------

for f in \
  "lib/core/analyzers/${RULE_NAME}_analyzer.dart" \
  "lib/custom_lint_rules/${RULE_NAME}.dart" \
  "lib/ripplearc_linter.dart" \
  "test/custom_lint_rules/${RULE_NAME}_test.dart" \
  "example/example_${RULE_NAME}_rule.dart" \
  "docs/${RULE_NAME}.md"; do
  [ -f "$f" ] && git add "$f"
done

# Catch anything else the agent created under the standard dirs
git add -A lib/ bin/ test/custom_lint_rules/ example/ docs/ rule_specs/ 2>/dev/null || true

# ---------------------------------------------------------------------------
# Commit
# ---------------------------------------------------------------------------

git diff --cached --quiet && { echo "Nothing staged to commit."; exit 1; }
git commit -m "Add ${RULE_NAME} linter rule"

# ---------------------------------------------------------------------------
# Push + PR
# ---------------------------------------------------------------------------

echo "Pushing branch $BRANCH_NAME..."
git push -u origin "$BRANCH_NAME"
_create_pr "$BASE_BRANCH" "$BRANCH_NAME" "$RULE_NAME"
